<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Cafe;

class CafeSeeder extends Seeder
{
    public function run(): void
    {
        $cafes = [
            [
                'name' => 'RAKO (Racikan Kopi)',
                'slug' => 'rako-racikan-kopi',
                'operating_hours' => '17.00-01.00',
                'wifi_quality' => 'QOC',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 14000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Titik Dua Kopi',
                'slug' => 'titik-dua-kopi',
                'operating_hours' => '10.00-00.00',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 15000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Seruma Kopi',
                'slug' => 'seruma-kopi',
                'operating_hours' => '15.00-00.00',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Lumayan',
                'noise_level' => 'Tenang',
                'air_conditioner' => true,
                'price_min' => 20000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Rline Coffee',
                'slug' => 'rline-coffee',
                'operating_hours' => '09.00-23.00',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 18000,
                'price_max' => 40000,
                'payment_method' => 'QRIS, Debit & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => '7 Grms Kopi',
                'slug' => '7-grms-kopi',
                'operating_hours' => '08.00-22.00',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Tenang',
                'air_conditioner' => true,
                'price_min' => 20000,
                'price_max' => 45000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Gage Kopi',
                'slug' => 'gage-kopi',
                'operating_hours' => '10.00-23.00',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Lumayan',
                'noise_level' => 'Ramai',
                'air_conditioner' => false,
                'price_min' => 15000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Klarifikopi',
                'slug' => 'klarifikopi',
                'operating_hours' => '16.00-01.00',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 18000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Warmindo Barokah Plus',
                'slug' => 'warmindo-barokah-plus',
                'operating_hours' => '24 Jam',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Ramai',
                'air_conditioner' => false,
                'price_min' => 5000,
                'price_max' => 20000,
                'payment_method' => 'Cash Only',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'KM02 Coffee & Workingspace',
                'slug' => 'km02-coffee-workingspace',
                'operating_hours' => '09.00-24.00',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Sangat Banyak',
                'noise_level' => 'Tenang',
                'air_conditioner' => true,
                'price_min' => 25000,
                'price_max' => 50000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Warmindo Nomsco',
                'slug' => 'warmindo-nomsco',
                'operating_hours' => '24 Jam',
                'wifi_quality' => 'Tidak Ada',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Ramai',
                'air_conditioner' => false,
                'price_min' => 6000,
                'price_max' => 15000,
                'payment_method' => 'Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Kedai Nyamin',
                'slug' => 'kedai-nyamin',
                'operating_hours' => '17.00-23.00',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Sedikit',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 10000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Dasaran Kopi',
                'slug' => 'dasaran-kopi',
                'operating_hours' => '15.00-23.30',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 18000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Burjo Mitro',
                'slug' => 'burjo-mitro',
                'operating_hours' => '24 Jam',
                'wifi_quality' => 'Tidak Ada',
                'power_outlets' => 'Sedikit',
                'noise_level' => 'Ramai',
                'air_conditioner' => false,
                'price_min' => 5000,
                'price_max' => 15000,
                'payment_method' => 'Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Warmindo Oumi',
                'slug' => 'warmindo-oumi',
                'operating_hours' => '07.00-22.00',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Lumayan',
                'noise_level' => 'Ramai',
                'air_conditioner' => false,
                'price_min' => 6000,
                'price_max' => 20000,
                'payment_method' => 'Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Mason Coffee & Brunch',
                'slug' => 'mason-coffee-brunch',
                'operating_hours' => '08.00-22.00',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Tenang',
                'air_conditioner' => true,
                'price_min' => 25000,
                'price_max' => 60000,
                'payment_method' => 'QRIS, Debit & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Sen Gu Coffee',
                'slug' => 'sen-gu-coffee',
                'operating_hours' => '14.00-23.00',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 18000,
                'price_max' => 40000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Mekar Kopi',
                'slug' => 'mekar-kopi',
                'operating_hours' => '16.00-00.00',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Lumayan',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 15000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
            [
                'name' => 'Koffie Rakjat',
                'slug' => 'koffie-rakjat',
                'operating_hours' => '09.00-23.00',
                'wifi_quality' => 'Kencang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 16000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
                'maps_url' => 'https://maps.google.com/',
            ],
        ];

        // Looping untuk memasukkan semua 18 data di atas ke database MySQL sekaligus
        foreach ($cafes as $cafe) {
            Cafe::create($cafe);
        }
    }
}