<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Cafe;
use Illuminate\Support\Str;

class CafeSeeder extends Seeder
{
    public function run(): void
    {
        $cafes = [
            [
                'name' => 'RAKO (Racikan Kopi)',
                'operating_hours' => '17.00 - 01.00',
                'maps_url' => 'https://maps.app.goo.gl/c5YFERBsQoQzw1pd9',
                'wifi_quality' => 'Tidak Ada',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 14000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=500',
            ],
            [
                'name' => 'Titik Dua Kopi',
                'operating_hours' => '10.00 - 00.00',
                'maps_url' => 'https://maps.app.goo.gl/VtcmoWQ3sCTWY3149',
                'wifi_quality' => 'Ngebut',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 15000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
            ],
            [
                'name' => 'Seruma Kopi',
                'operating_hours' => '15.00 - 00.00',
                'maps_url' => 'https://maps.app.goo.gl/SN6eJYneESASbv7Q9',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 20000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500',
            ],
            [
                'name' => 'Rline Coffee',
                'operating_hours' => '08.00 - 22.00',
                'maps_url' => 'https://maps.app.goo.gl/vemRzudHdpChQ67k8',
                'wifi_quality' => 'Tidak Ada',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 10000,
                'price_max' => 20000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Low Budget',
                'image_url' => 'https://images.unsplash.com/photo-1559925393-8be08e367839?w=500',
            ],
            [
                'name' => '7 Grms Kopi',
                'operating_hours' => '08.07 - 23.07',
                'maps_url' => 'https://maps.app.goo.gl/L1553Tmh5L8b3GbT9',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 20000,
                'price_max' => 27000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1442512595333-e892d19163f4?w=500',
            ],
            [
                'name' => 'Gage Kopi',
                'operating_hours' => '09.00 - 22.00',
                'maps_url' => 'https://maps.app.goo.gl/ns97xgh1KmTYr7sN8',
                'wifi_quality' => 'Tidak Ada',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sunyi',
                'air_conditioner' => false,
                'price_min' => 8000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1512568400610-66da283f508a?w=500',
            ],
            [
                'name' => 'Klarifikopi',
                'operating_hours' => '14.00 - 22.00',
                'maps_url' => 'https://maps.app.goo.gl/ZskWMCMkL8aFdwJD6',
                'wifi_quality' => 'Tidak Ada',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 5000,
                'price_max' => 16000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Low Budget',
                'image_url' => 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=500',
            ],
            [
                'name' => 'Warmindo Barokah Plus',
                'operating_hours' => '10.00 - 01.00',
                'maps_url' => 'https://maps.app.goo.gl/5MfN8QXcVEzEzkTGA',
                'wifi_quality' => 'Lemot',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Bising',
                'air_conditioner' => true,
                'price_min' => 4000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1560624052-449f5ddf0032?w=500',
            ],
            [
                'name' => 'KM02 Coffee & Workingspace',
                'operating_hours' => '08.00 - 23.30',
                'maps_url' => 'https://maps.app.goo.gl/tbx6CgQrJL6c3ckj9',
                'wifi_quality' => 'Ngebut',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 22000,
                'price_max' => 65000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Mahal',
                'image_url' => 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=500',
            ],
            [
                'name' => 'Warmindo Nomsco',
                'operating_hours' => '10.00 - 01.00',
                'maps_url' => 'https://maps.app.goo.gl/peF3GoFirRsvr3sT9',
                'wifi_quality' => 'Ngebut',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 5000,
                'price_max' => 20000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Low Budget',
                'image_url' => 'https://images.unsplash.com/photo-1541167760496-1628856ab77a?w=500',
            ],
            [
                'name' => 'Kedai Nyamin',
                'operating_hours' => '12.00 - 00.00',
                'maps_url' => 'https://maps.app.goo.gl/EDMhpfmQaUfs2d2A7',
                'wifi_quality' => 'Ngebut',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sunyi',
                'air_conditioner' => true,
                'price_min' => 10000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=500',
            ],
            [
                'name' => 'Dasaran Kopi',
                'operating_hours' => '07.30 - 00.00',
                'maps_url' => 'https://maps.app.goo.gl/MATVeQwMdsxdcu6y5',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 13000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=500',
            ],
            [
                'name' => 'Burjo Mitro',
                'operating_hours' => '07.30 - 23.30',
                'maps_url' => 'https://maps.app.goo.gl/EEHS2MH9N5QvQs7HA',
                'wifi_quality' => 'Ngebut',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Bising',
                'air_conditioner' => false,
                'price_min' => 5000,
                'price_max' => 45000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Mahal',
                'image_url' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500',
            ],
            [
                'name' => 'Warmindo Oumi',
                'operating_hours' => '15.00 - 22.00',
                'maps_url' => 'https://maps.app.goo.gl/irSpktUYTEx53p3AA',
                'wifi_quality' => 'Ngebut',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 5000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=500',
            ],
            [
                'name' => 'Mason Coffee & Brunch',
                'operating_hours' => '07.00 - 10.00',
                'maps_url' => 'https://maps.app.goo.gl/HH2P2PaWt4safKtY7',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 12000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500',
            ],
            [
                'name' => 'Sen Gu Coffee',
                'operating_hours' => '17.00 - 23.30',
                'maps_url' => 'https://maps.app.goo.gl/Zb9Dg7NqTn5NwfeT7',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sunyi',
                'air_conditioner' => false,
                'price_min' => 15000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1506619216599-9d16ad09050d?w=500',
            ],
            [
                'name' => 'Mekar Kopi',
                'operating_hours' => '11.00 - 00.00',
                'maps_url' => 'https://maps.app.goo.gl/vwyiDWqCMYRCbMki7',
                'wifi_quality' => 'Ngebut',
                'power_outlets' => 'Banyak',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 16000,
                'price_max' => 65000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Mahal',
                'image_url' => 'https://images.unsplash.com/photo-1481833761820-0509d3bea172?w=500',
            ],
            [
                'name' => 'Koffie Rakjat',
                'operating_hours' => '16.00 - 00.00',
                'maps_url' => 'https://maps.app.goo.gl/u2FQqA3xX7Doa13V8',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 13000,
                'price_max' => 23000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1512070639113-145749f7e07e?w=500',
            ],
            [
                'name' => 'Warkop Mas Amba',
                'operating_hours' => '09.00 - 23.30',
                'maps_url' => 'https://maps.app.goo.gl/fgKaN78qjWMPQjv79',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 8000,
                'price_max' => 18000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Low Budget',
                'image_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=500',
            ],
            [
                'name' => 'Terikat Kopi',
                'operating_hours' => '10.00 - 02.00',
                'maps_url' => 'https://maps.app.goo.gl/cVEPdx9Dd8WAbcbJ6',
                'wifi_quality' => 'Lemot',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 14000,
                'price_max' => 38000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Mahal',
                'image_url' => 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
            ],
            [
                'name' => 'Cafe Sunset View',
                'operating_hours' => '14.00 - 22.00',
                'maps_url' => 'https://maps.app.goo.gl/59oeDAhVgAxttS7d7',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 9000,
                'price_max' => 22000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500',
            ],
            [
                'name' => 'Skymindo',
                'operating_hours' => '17.00 - 23.00',
                'maps_url' => 'https://maps.app.goo.gl/chJXHogdBk37gmXd7',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 7000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1559925393-8be08e367839?w=500',
            ],
            [
                'name' => 'Tatap Muka Coffee & Work',
                'operating_hours' => '11.00 - 23.00',
                'maps_url' => 'https://maps.app.goo.gl/3Mk1SM6viJB8Tn6W6',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 25000,
                'price_max' => 50000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Mahal',
                'image_url' => 'https://images.unsplash.com/photo-1442512595333-e892d19163f4?w=500',
            ],
            [
                'name' => 'Warkop Prama',
                'operating_hours' => '07.00 - 00.00',
                'maps_url' => 'https://maps.app.goo.gl/R9sdD9yP6Z9cRNSb7',
                'wifi_quality' => 'Tidak Ada',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => false,
                'price_min' => 7000,
                'price_max' => 15000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Low Budget',
                'image_url' => 'https://images.unsplash.com/photo-1512568400610-66da283f508a?w=500',
            ],
            [
                'name' => 'PIMA - Coffee & Clothing',
                'operating_hours' => '09.00 - 23.00',
                'maps_url' => 'https://maps.app.goo.gl/k9yPcWSttoUxkTvT7',
                'wifi_quality' => 'Ngebut',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sunyi',
                'air_conditioner' => true,
                'price_min' => 15000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=500',
            ],
            [
                'name' => 'Arunika Coffee and Space',
                'operating_hours' => '08.00 - 22.00',
                'maps_url' => 'https://maps.app.goo.gl/Ry6G1nHs7B2Psu2Z6',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 15000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Sedang',
                'image_url' => 'https://images.unsplash.com/photo-1541167760496-1628856ab77a?w=500',
            ],
            [
                'name' => 'Kopi Kenangan',
                'operating_hours' => '08.00 - 23.00',
                'maps_url' => 'https://maps.app.goo.gl/BMBdVGHSFiVMzSzNA',
                'wifi_quality' => 'Sedang',
                'power_outlets' => 'Terbatas',
                'noise_level' => 'Sedang',
                'air_conditioner' => true,
                'price_min' => 18000,
                'price_max' => 50000,
                'payment_method' => 'QRIS & Cash',
                'price_category' => 'Mahal',
                'image_url' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=500',
            ]
        ];

        foreach ($cafes as $cafe) {
            // Membuat slug secara dinamis dari nama cafe agar tidak bentrok
            $cafe['slug'] = Str::slug($cafe['name']);
            Cafe::create($cafe);
        }
    }
}