<?php

namespace Database\Seeders;

use App\Models\Cafe;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CafeSeeder extends Seeder
{
    public function run(): void
    {
        $cafes = [
            [
                'name' => 'RAKO (Racikan Kopi)',
                'jam_operasional' => '18.00 - 01.00',
                'maps_url' => 'maps.app.goo.gl/c5YFERBsQoQzw1pd9',
                'foto_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24',
                'wifi' => 'No Wifi',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => false,
                'price_min' => 14000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Titik Dua Kopi',
                'jam_operasional' => '10.00 - 00.00',
                'maps_url' => 'maps.app.goo.gl/VtcmoWQ3sCTWY3149',
                'foto_url' => 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf',
                'wifi' => 'Kenceng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 15000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Seruma Kopi',
                'jam_operasional' => '15.00 - 00.00',
                'maps_url' => 'maps.app.goo.gl/SN6eJYneESASbv7Q9',
                'foto_url' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93',
                'wifi' => 'Sedeng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Sedang',
                'ac' => false,
                'price_min' => 20000,
                'price_max' => 35000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Rline Coffee',
                'jam_operasional' => '08.00 - 22.00',
                'maps_url' => 'maps.app.goo.gl/vemRzudHdpChQ67k8',
                'foto_url' => 'https://images.unsplash.com/photo-1559925393-8be08e367839',
                'wifi' => 'No Wifi',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => false,
                'price_min' => 10000,
                'price_max' => 20000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => '7 Grms Kopi',
                'jam_operasional' => '08.07 - 23.07',
                'maps_url' => 'maps.app.goo.gl/L1553Tmh5L8b3GbT9',
                'foto_url' => 'https://images.unsplash.com/photo-1442512595333-e892d19163f4',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => false,
                'price_min' => 20000,
                'price_max' => 27000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Gage Kopi',
                'jam_operasional' => '09.00 - 22.00',
                'maps_url' => 'maps.app.goo.gl/ns97xgh1KmTYr7sN8',
                'foto_url' => 'https://images.unsplash.com/photo-1512568400610-66da283f508a',
                'wifi' => 'No Wifi',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sunyi',
                'ac' => false,
                'price_min' => 8000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Klarifikopi',
                'jam_operasional' => '14.00 - 22.00',
                'maps_url' => 'maps.app.goo.gl/ZskWMCMkL8aFdwJD6',
                'foto_url' => 'https://images.unsplash.com/photo-1507133750040-4a8f57021571',
                'wifi' => 'No Wifi',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 5000,
                'price_max' => 16000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Warmindo Barokah Plus',
                'jam_operasional' => '10.00 - 01.00',
                'maps_url' => 'maps.app.goo.gl/5MfN8QXcVEzEzkTGA',
                'foto_url' => 'https://images.unsplash.com/photo-1560624052-449f5ddf0032',
                'wifi' => 'Lemot',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Ramai',
                'ac' => true,
                'price_min' => 4000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'KM02 Coffee & Workingspace',
                'jam_operasional' => '08.00 - 23.30',
                'maps_url' => 'maps.app.goo.gl/tbx6CgQrJL6c3ckj9',
                'foto_url' => 'https://images.unsplash.com/photo-1453614512568-c4024d13c247',
                'wifi' => 'Kenceng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 22000,
                'price_max' => 65000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Warmindo Nomsco',
                'jam_operasional' => '10.00 - 01.00',
                'maps_url' => 'maps.app.goo.gl/peF3GoFirRsvr3sT9',
                'foto_url' => 'https://images.unsplash.com/photo-1541167760496-1628856ab77a',
                'wifi' => 'Kenceng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 5000,
                'price_max' => 20000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Kedai Nyamin',
                'jam_operasional' => '12.00 - 00.00',
                'maps_url' => 'maps.app.goo.gl/EDMhpfmQaUfs2d2A7',
                'foto_url' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de',
                'wifi' => 'Kenceng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Sunyi',
                'ac' => true,
                'price_min' => 10000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Dasaran Kopi',
                'jam_operasional' => '07.30 - 00.00',
                'maps_url' => 'maps.app.goo.gl/MATVeQwMdsxdcu6y5',
                'foto_url' => 'https://images.unsplash.com/photo-1511920170033-f8396924c348',
                'wifi' => 'Sedeng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 13000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Burjo Mitro',
                'jam_operasional' => '07.30 - 23.30',
                'maps_url' => 'maps.app.goo.gl/EEHS2MH9N5QvQs7HA',
                'foto_url' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c',
                'wifi' => 'Kenceng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Ramai',
                'ac' => false,
                'price_min' => 5000,
                'price_max' => 45000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Warmindo Oumi',
                'jam_operasional' => '15.00 - 22.00',
                'maps_url' => 'maps.app.goo.gl/irSpktUYTEx53p3AA',
                'foto_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
                'wifi' => 'Kenceng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 5000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Mason Coffee & Brunch',
                'jam_operasional' => '07.00 - 10.00',
                'maps_url' => 'maps.app.goo.gl/HH2P2PaWt4safKtY7',
                'foto_url' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 12000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Sen Gu Coffee',
                'jam_operasional' => '17.00 - 23.30',
                'maps_url' => 'maps.app.goo.gl/Zb9Dg7NqTn5NwfeT7',
                'foto_url' => 'https://images.unsplash.com/photo-1506619216599-9d16ad09050d',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sunyi',
                'ac' => false,
                'price_min' => 15000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Mekar Kopi',
                'jam_operasional' => '11.00 - 00.00',
                'maps_url' => 'maps.app.goo.gl/vwyiDWqCMYRCbMki7',
                'foto_url' => 'https://images.unsplash.com/photo-1481833761820-0509d3bea172',
                'wifi' => 'Kenceng',
                'colokan' => 'Banyak',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 16000,
                'price_max' => 65000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Koffie Rakjat',
                'jam_operasional' => '16.00 - 00.00',
                'maps_url' => 'maps.app.goo.gl/u2FQqA3xX7Doa13V8',
                'foto_url' => 'https://images.unsplash.com/photo-1512070639113-145749f7e07e',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => false,
                'price_min' => 13000,
                'price_max' => 23000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Warkop Mas Amba',
                'jam_operasional' => '09.00 - 23.30',
                'maps_url' => 'maps.app.goo.gl/fgKaN78qjWMPQjv79',
                'foto_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 8000,
                'price_max' => 18000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Terikat Kopi',
                'jam_operasional' => '10.00 - 02.00',
                'maps_url' => 'maps.app.goo.gl/cVEPdx9Dd8WAbcbJ6',
                'foto_url' => 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf',
                'wifi' => 'Lemot',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => false,
                'price_min' => 14000,
                'price_max' => 38000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Cafe Sunset View',
                'jam_operasional' => '14.00 - 22.00',
                'maps_url' => 'maps.app.goo.gl/59oeDAhVgAxttS7d7',
                'foto_url' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => false,
                'price_min' => 9000,
                'price_max' => 22000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Skymindo',
                'jam_operasional' => '17.00 - 23.00',
                'maps_url' => 'maps.app.goo.gl/chJXHogdBk37gmXd7',
                'foto_url' => 'https://images.unsplash.com/photo-1559925393-8be08e367839',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 7000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Tatap Muka Coffee & Work',
                'jam_operasional' => '11.00 - 23.00',
                'maps_url' => 'maps.app.goo.gl/3Mk1SM6viJB8Tn6W6',
                'foto_url' => 'https://images.unsplash.com/photo-1442512595333-e892d19163f4',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 25000,
                'price_max' => 50000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Warkop Prama',
                'jam_operasional' => '07.00 - 00.00',
                'maps_url' => 'maps.app.goo.gl/R9sdD9yP6Z9cRNSb7',
                'foto_url' => 'https://images.unsplash.com/photo-1512568400610-66da283f508a',
                'wifi' => 'No Wifi',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => false,
                'price_min' => 7000,
                'price_max' => 15000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'PIMA - Coffee & Clothing',
                'jam_operasional' => '09.00 - 23.00',
                'maps_url' => 'maps.app.goo.gl/k9yPcWSttoUxkTvT7',
                'foto_url' => 'https://images.unsplash.com/photo-1453614512568-c4024d13c247',
                'wifi' => 'Kenceng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sunyi',
                'ac' => true,
                'price_min' => 15000,
                'price_max' => 30000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Arunika Coffee and Space',
                'jam_operasional' => '08.00 - 22.00',
                'maps_url' => 'maps.app.goo.gl/Ry6G1nHs7B2Psu2Z6',
                'foto_url' => 'https://images.unsplash.com/photo-1541167760496-1628856ab77a',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 15000,
                'price_max' => 25000,
                'payment_method' => 'QRIS & Cash',
            ],
            [
                'name' => 'Kopi Kenangan',
                'jam_operasional' => '08.00 - 23.00',
                'maps_url' => 'maps.app.goo.gl/BMBdVGHSFiVMzSzNA',
                'foto_url' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de',
                'wifi' => 'Sedeng',
                'colokan' => 'Terbatas',
                'kebisingan' => 'Sedang',
                'ac' => true,
                'price_min' => 18000,
                'price_max' => 50000,
                'payment_method' => 'QRIS & Cash',
            ],
        ];

        foreach ($cafes as $cafe) {
            $cafe['slug'] = Str::slug($cafe['name']);
            Cafe::create($cafe);
        }
    }
}